### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by germ13** [atom/snippets#102]
[Enter steps to reproduce below:]

1. Using Xubuntu 14.04
2. Opened atom from "Start" menu.

**Atom Version**: 0.165.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.60.0

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:364:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:101:14)
  at /usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61
  at File.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at File.module.exports.Emitter.on (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:48:14)
  at File.module.exports.File.on (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:76:40)
  at /usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:164:30
  at Object.oncomplete (fs.js:93:15)
  at Ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as setSize] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:69:19)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Could you please upgrade Atom to the latest version (currently 0.176.0) and see if this still happens?

**Comment by germ13** [comment]
@50Wliu thanks for suggestion and prompt reply.

Upgraded to 0.176.0. 

Got multiple errors (screenshot)
![atom](https://cloud.githubusercontent.com/assets/146168/5926339/37adc4d2-a61f-11e4-9eef-af061a6bf10a.png)

Followed [link](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path) as suggested.  Executed ` sudo sysctl fs.inotify.max_user_watches=32768` and Atom opened up without any issues.

Is this solution a workaround to a bigger or inherent problem in the code? Should I expect Atom to run fine at some point without the above shell command?

**Comment by germ13** [comment]
Read the [reference issue](https://github.com/atom/atom/issues/2082) on above link. Got my answer.
