### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

### ISSUE THREAD

**Issue by redtwiggy** [atom/snippets#111]
1. Pressing twice alt+shift+s

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.76.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:375

TypeError: Cannot read property 'getLastCursor' of undefined
  at Object.module.exports.getSnippets (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:375:22)
  at SnippetsAvailable.module.exports.SnippetsAvailable.populate (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets-available.js:54:41)
  at SnippetsAvailable.module.exports.SnippetsAvailable.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets-available.js:39:14)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets-available.js:25:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -4:21.9 core:confirm (atom-text-editor.editor.mini)
     -3:56.4 core:select-all (atom-text-editor.editor.mini)
     -3:49.6 core:confirm (atom-text-editor.editor.mini)
     -3:21.1 core:close (atom-text-editor.editor.mini)
     -3:20.1 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -2:35.7 core:confirm (atom-text-editor.editor.mini)
     -1:27.6 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:26.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:26.0 core:cancel (atom-text-editor.editor.mini)
     -1:25.5 application:new-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:33.9 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -0:26.2 application:new-file (ul.list-inline.tab-bar.inset-panel)
  3x -0:23.3 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
  4x -0:18.3 snippets:available (atom-text-editor.editor.is-focused)
     -0:10.1 core:save-as (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -0:00.9 snippets:available (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
color-picker, v1.4.4
language-protobuf, v0.2.1
remember-session, v0.5.1
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it will be fixed in the next Atom release, 0.185
