### ISSUE TITLE
Error deactivating package 'snippets' TypeError: undefined is not a function

### ISSUE THREAD

**Issue by joefitzgerald** [atom/snippets#125]
I'm getting this when running specs for `autocomplete-plus` - this is a new error (see https://travis-ci.org/atom-community/autocomplete-plus/builds/56997762 for a repro of this not on my machine):

```
Error deactivating package 'snippets' TypeError: undefined is not a function
  at Object.module.exports.deactivate (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:90:15)
  at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app/src/package.js:609:21)
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:495:12)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:480:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.deactivatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:474:19)
  at [object Object].<anonymous> (/Applications/Atom.app/Contents/Resources/app/spec/spec-helper.coffee:147:17)
  at [object Object].jasmine.Block.execute (/Applications/Atom.app/Contents/Resources/app/vendor/jasmine.js:1070:17)
  at [object Object].jasmine.Queue.next_ (/Applications/Atom.app/Contents/Resources/app/vendor/jasmine.js:2102:31)
  at [object Object].onComplete (/Applications/Atom.app/Contents/Resources/app/vendor/jasmine.js:2098:18)
  at [object Object].jasmine.WaitsForBlock.MultiCompletion.attemptCompletion (/Applications/Atom.app/Contents/Resources/app/vendor/jasmine.js:2648:8)
  at /Applications/Atom.app/Contents/Resources/app/vendor/jasmine.js:2658:10
  at process._tickCallback (node.js:367:9)
module.exports.Package.deactivate /Applications/Atom.app/Contents/Resources/app/src/package.js:614
```

This has the side-effect of:

```
Error: Leaking subscriptions for paths: /Users/jfitzgerald/.atom/snippets.cson
at ensureNoPathSubscriptions (/Applications/Atom.app/Contents/Resources/app/spec/spec-helper.coffee:174:15)
at /Applications/Atom.app/Contents/Resources/app/spec/spec-helper.coffee:166:3
```

... when running interactively in the spec runner.

**Comment by joefitzgerald** [comment]
... and this line looks to be the culprit: https://github.com/atom/snippets/blob/0d6106401a49ba82860a8ea27ec08105968766a8/lib/snippets.coffee#L58

**Comment by benogle** [comment]
I fixed it in the latest version of snippets. It will be out on atom 190,
but it's on master now
