### ISSUE TITLE
Uncaught Error: end pattern with unmatched parenthesis

### ISSUE THREAD

**Issue by shikkaba** [atom/snippets#167]
[Enter steps to reproduce below:]

1. Changed file type to Wordpress

**Atom Version**: 1.0.11
**System**: Mac OS X 10.9.5
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.95.0

### Stack Trace

Uncaught Error: end pattern with unmatched parenthesis

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

Error: end pattern with unmatched parenthesis
  at Error (native)
  at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
  at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
  at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
  at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
  at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
  at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:557:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:543:19)
  at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:496:34)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:505:10)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:384:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:648:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:802:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:771:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:24:35
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at new SnippetExpansion (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:21:19)
  at Object.module.exports.insert (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippets.js:485:14)
  at SnippetsAvailable.module.exports.SnippetsAvailable.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippets-available.js:90:37)
  at SnippetsAvailable.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  7x -5:01.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:23.2.0 settings-view:check-for-package-updates (atom-text-editor.editor)
     -1:21.4.0 grammar-selector:show (atom-text-editor.editor)
     -0:45.8.0 snippets:show (atom-text-editor.editor.is-focused)
     -0:38.1.0 snippets:available (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
autocomplete-php, v0.3.7
color-picker, v2.0.11
css-snippets, v0.8.0
docs-snippets, v0.8.0
emmet, v2.3.12
highlight-line, v0.11.0
javascript-snippets, v1.0.0
linter, v1.5.0
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-js-yaml, v1.1.1
linter-jshint, v1.1.5
linter-php, v1.0.3
linter-phpcs, v1.0.6
linter-phpmd, v1.0.0
linter-scss-lint, v2.0.0
linter-tidy, v1.0.1
minimap, v4.13.2
tree-view-git-status, v0.1.2
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to tomvdv/atom-wordpress#3
