### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jamiepeloquin** [atom/snippets#187]
[Enter steps to reproduce below:]
1. Open package.json
2. Start adding "foundation" to the dependencies - this is when it threw the error.

**Atom Version**: 1.4.0-beta0
**System**: Mac OS X 10.11.2
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

TypeError: Cannot read property 'split' of undefined
    at Selection.module.exports.Selection.insertText (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/selection.js:465:28)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:25:43
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:24:35
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at new SnippetExpansion (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippet-expansion.js:21:19)
    at Object.module.exports.insert (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippets.js:540:14)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:563:39
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1216:26)
    at AutocompleteManager.module.exports.AutocompleteManager.replaceTextWithMatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:549:26)
    at AutocompleteManager.replaceTextWithMatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.confirm (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:501:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at SuggestionList.module.exports.SuggestionList.confirm (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:135:27)
    at SuggestionList.confirm (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:3:61)
    at autocomplete-suggestion-list.SuggestionListElement.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:258:27)
    at autocomplete-suggestion-list.onmouseup (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list-element.js:119:23)
```
### Commands

```
     -0:42.7.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:33.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:33.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:28.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.4.0 editor:newline (atom-text-editor.editor.is-focused.omnisharp-editor)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/jpeloquin/OneDrive/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
atom-typescript, v7.14.2
atom-yeoman, v0.3.15
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-php, v0.3.7
editorconfig, v1.2.2
html-entities, v0.4.0
json-schema, v0.1.15
language-apache, v1.3.0
language-powershell, v2.1.0
linter, v1.11.3
linter-htmlhint, v0.2.1
linter-jsonlint, v1.1.1
linter-phpcs, v1.3.0
omnisharp-atom, v0.26.7
pretty-json, v0.4.1
ssh-config, v0.10.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports.
