### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by jdkizer9** [atom/snippets#198]
Tried deleting a file and an error was thrown.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v1.0.1

### Stack Trace

Uncaught SyntaxError: Unexpected token ILLEGAL

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/snippets/lib/snippets.js:34

SyntaxError: Unexpected token ILLEGAL
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:484:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:419:19)
    at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:475:48)
    at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:187:26)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:14.1.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2
react, v0.14.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
What file did you delete?

**Comment by 50Wliu** [comment]
Closing until more information is provided.
