### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by francodacosta** [atom/snippets#95]
[Enter steps to reproduce below:]

1. not sure how to reproduce, usually happens when clicking ctrl + / (to comment a line)
sometimes happens when pressing tab on an emplty line

**Atom Version**: 0.167.0
**System**: linux 3.17.7-200.fc20.x86_64
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.60.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/local/share/atom/resources/app/src/config.js:189

TypeError: undefined is not a function
  at Config.module.exports.Config.getAll (/usr/local/share/atom/resources/app/src/config.js:189:57)
  at Config.module.exports.Config.settingsForScopeDescriptor (/usr/local/share/atom/resources/app/src/config.js:822:22)
  at Object.module.exports.getSnippets (/usr/local/share/atom/resources/app/node_modules/snippets/lib/snippets.js:340:27)
  at Object.module.exports.snippetToExpandUnderCursor (/usr/local/share/atom/resources/app/node_modules/snippets/lib/snippets.js:358:23)
  at atom-text-editor.subscriptions.add.atom.commands.add.snippets:expand (/usr/local/share/atom/resources/app/node_modules/snippets/lib/snippets.js:46:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -7:46.7 core:move-down (atom-text-editor.editor.is-focused)
     -7:46.2 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:29.8 core:save (atom-text-editor.editor.is-focused)
     -4:12.1 core:backspace (atom-text-editor.editor)
  4x -4:10.8 core:move-down (atom-text-editor.editor)
     -3:59.5 core:save (atom-text-editor.editor)
     -3:54.5 core:undo (atom-text-editor.editor)
     -0:01.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.3 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:00.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:00.0 snippets:expand (atom-text-editor.editor.is-focused)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
monokai-dark, v1.0.0
project-manager, v1.14.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by maxbrunsfeld** [comment]
This was a compatibility error on my part. It is fixed in snippets 0.61, which will be released with the next version of Atom.

**Comment by francodacosta** [comment]
@maxbrunsfeld and when will that be ?

My version of atom was build from the master branch a few hours ago!

**Comment by maxbrunsfeld** [comment]
Oh. Is it possible you haven't updated the dependencies? You're using an old version of `snippets`.
